"""
State definitions for the Literature Scout Agent.

Design principle: Lists that GROW across nodes use Annotated[List, operator.add].
Lists that get REPLACED each node (like papers_to_read) are plain List.
This distinction is critical — getting it wrong causes silent data loss in LangGraph.
"""

import operator
from typing import TypedDict, List, Optional, Annotated


class Paper(TypedDict):
    """Raw paper metadata — populated by search + PDF reader nodes."""
    paper_id: str           # arxiv short ID or S2 paper ID
    title: str
    authors: List[str]
    abstract: str
    year: Optional[int]
    pdf_url: Optional[str]
    source: str             # "arxiv" | "semantic_scholar" | "semantic_scholar_reference"
    s2_id: Optional[str]    # Semantic Scholar ID (needed for citation graph)
    full_text: Optional[str]  # Populated after PDF read; None until then


class ExtractedPaper(TypedDict):
    """
    Structured extraction — this is what gets written to ChromaDB
    and consumed by the Feasibility Critic agent downstream.
    Schema is fixed; critic depends on these exact fields.
    """
    paper_id: str
    title: str
    authors: List[str]
    year: Optional[int]
    source: str
    abstract: str
    # ── LLM-extracted fields ──
    problem_addressed: str      # One sentence: what problem does this solve?
    proposed_method: str        # One sentence: what is the approach?
    key_assumptions: List[str]  # What must be true for this method to work?
    results_metrics: str        # Quantitative results, benchmarks, accuracy
    constraints: List[str]      # Limitations — fed directly to feasibility critic


class ScoutState(TypedDict):
    """
    Full state of the Literature Scout graph.

    Accumulator fields (Annotated with operator.add):
        These are lists that nodes ADD to rather than replace.
        LangGraph merges them across node outputs automatically.

    Plain list fields:
        These are replaced wholesale each time a node updates them.
        Used for "current batch" processing queues.
    """
    problem_statement: str

    # Generated by generate_queries node
    search_queries: List[str]

    # Accumulates across search + citation rounds
    raw_papers: Annotated[List[Paper], operator.add]

    # Replaced each round with the current batch to process
    papers_to_read: List[Paper]

    # Accumulates papers after PDF fetch
    papers_read: Annotated[List[Paper], operator.add]

    # Accumulates after LLM extraction — these go to ChromaDB
    extracted_papers: Annotated[List[ExtractedPaper], operator.add]

    # S2 IDs of top papers — used to seed citation graph walk
    citation_seeds: List[str]

    # Papers discovered via citation graph (references of key papers)
    citation_papers: Annotated[List[Paper], operator.add]

    # How many citation rounds have run (stops infinite loops)
    citation_round: int

    # Papers written to ChromaDB successfully
    stored_count: int

    # Human-readable log — accumulates across all nodes
    messages: Annotated[List[str], operator.add]
